### ISSUE TITLE
Integration with SIEM

### ISSUE THREAD

**Issue by sunflower-1** [TheHive-Project/TheHiveDocs#30]
Hello,

How can I receive alerts from SIEM?
Is there any tutorial guide?

Thank you very much

**Comment by saadkadhi** [comment]
There are sadly no tutorials but the basic steps are the following:

- Option A: your SIEM has the ability to make API calls triggered by specific events. Then in that case, read the [API documentation](https://github.com/TheHive-Project/TheHiveDocs/tree/master/api) and interface your SIEM to feed alerts to TheHive or open cases right away (if a critical security event is observed for example).

- Option B: your SIEM can call an external script upon a specific rule being triggered. In that case, and preferably, make a Python script which relies on [TheHive4py](https://github.com/TheHive-Project/TheHive4py/) library to package the alert and send it to TheHive. As stated above, you could also make your Python script create a case depending on certain conditions instead of an alert.

- Option C: your SIEM can send an email when generating an alert. In that case, configure your SIEM to send the alert to a given mailbox and create a Python script which will poll said mailbox at regular intervals, parse the new emails, package them as alerts and send them to TheHive using [TheHive4py](https://github.com/TheHive-Project/TheHive4py/).

Please get a look at the following repositories for sample code:

- [TheHive4py](https://github.com/TheHive-Project/TheHive4py/)
- [Zerofox2TH](https://github.com/TheHive-Project/Zerofox2TH) alert feeder
- [DigitalShadows2TH](https://github.com/TheHive-Project/DigitalShadows2TH) alert feeder

If that's not enough and you are looking into professional help (for a fee), we can provide that through Creative Source, the non-profit organization we have created to further support users. Drop us a mail at support@thehive-project.org if that is something you want to consider.

Happy coding.
